namespace ET
{
    public enum UnitType: byte
    {
        Boss = 0,
        Monster = 1,
        Warrior =2,
        Drunkard=3,
        StoneBoy=4,
        Acrobat=5,
        Master=6,
        Peot=7,
        WarriorWeapon=8,
        DrunkardWeapon=9,
        StoneBoyWeapon=10,
        AcrobatWeapon=11,
        MasterWeapon=12,
        PeotWeapon=13,
        DrunkardSkill=14,
        StoneBoySkill=15,
        NormalAttackEffect = 16,
        DrunkardAttackEffect = 17,
        HeroSpawnEffect = 18,
        AddAttackSpeedEffect = 19,
        AddAttackDamageEffect = 20,
        MasterSkill = 21,
        StoneBoySkillWeapon = 22,
        Player = 23,
        SmallMonster = 24,
        MiddleMonster = 25,
        BigMonster = 26,
        EnemyDeadEffect = 27,
        Buffalo = 28,
        Fox = 29,
        Rebbit = 30,
        Cheetah = 31,
        Octopus = 32,
        BuffaloWeapon = 33,
        FoxWeapon = 34,
        RebbitWeapon = 35,
        RebbitSkill = 36,
        RebbitSkillEffect = 37,
    }
}